name: Deploy Backend
on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: EC2-AWS
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.1' 
      - name: Run tests
        run: go test -v ./...
        working-directory: ./backend
      - name: Build the Go application
        run: |
          cd backend
          go build -o server ./cmd/main.go
      
      - name: Deploy binary to EC2 with SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: |
           ${{ secrets.EC2_SSH_KEY }}
          source: "backend/server" 
          target: "~/pasteCTL/backend/"

      - name: SSH and Restart Service
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo systemctl restart paste-backend